### ISSUE TITLE
Update to Discord.JS V14

### ISSUE THREAD

**Issue by lucadsign** [GirlsFromPanema/bottodir#33]

**Comment by vKxni** [comment]
Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team. 

Koni.

**Comment by lucadsign** [comment]
> Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> 
> Koni.

You could remove the commands that you cant update, and the v13 will be lately deprecated.

**Comment by vKxni** [comment]
> > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > Koni.
> 
> You could remove the commands that you cant update, and the v13 will be lately deprecated.

I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)

**Comment by lucadsign** [comment]
> > > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > > Koni.
> > 
> > 
> > You could remove the commands that you cant update, and the v13 will be lately deprecated.
> 
> I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)

Yeaah! I want that :)

**Comment by vKxni** [comment]
> > > > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > > > Koni.
> > > 
> > > 
> > > You could remove the commands that you cant update, and the v13 will be lately deprecated.
> > 
> > 
> > I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)
> 
> Yeaah! I want that :)

Do you have any ideas for commands etc.? Do you want to contribute too?

**Comment by lucadsign** [comment]
> > > > > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > > > > Koni.
> > > > 
> > > > 
> > > > You could remove the commands that you cant update, and the v13 will be lately deprecated.
> > > 
> > > 
> > > I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)
> > 
> > 
> > Yeaah! I want that :)
> 
> Do you have any ideas for commands etc.? Do you want to contribute too?

Yup! You can check out my bot [Aumount](https://github.com/Sev6nOfficial/aumount-docs/blob/main/README.md)!

**Comment by vKxni** [comment]
> > > > > > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > > > > > Koni.
> > > > > 
> > > > > 
> > > > > You could remove the commands that you cant update, and the v13 will be lately deprecated.
> > > > 
> > > > 
> > > > I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)
> > > 
> > > 
> > > Yeaah! I want that :)
> > 
> > 
> > Do you have any ideas for commands etc.? Do you want to contribute too?
> 
> Yup! You can check out my bot [Aumount](https://github.com/Sev6nOfficial/aumount-docs/blob/main/README.md)!

Awesome. What ideas do you have for now?

**Comment by lucadsign** [comment]
I do 

> > > > > > > Sadly I wont be able to update Bottodir to v14. It is running on V13 though which is still supported by the discord.js team.
> > > > > > > Koni.
> > > > > > 
> > > > > > 
> > > > > > You could remove the commands that you cant update, and the v13 will be lately deprecated.
> > > > > 
> > > > > 
> > > > > I was talking about the whole bot. If you have any ideas then I can rewrite bottodir completely, but with features that are more special and that almost no other bot has. What do you think? You could help too, or your friends! ;)
> > > > 
> > > > 
> > > > Yeaah! I want that :)
> > > 
> > > 
> > > Do you have any ideas for commands etc.? Do you want to contribute too?
> > 
> > 
> > Yup! You can check out my bot [Aumount](https://github.com/Sev6nOfficial/aumount-docs/blob/main/README.md)!
> 
> Awesome. What ideas do you have for now?

I do have some, but do you want to see my bot?

**Comment by lucadsign** [comment]
Bro?

**Comment by vKxni** [comment]
?

**Comment by lucadsign** [comment]
Why u closed
